[package]
name = "eq677"
version = "0.1.0"
edition = "2024"

[dependencies]
egg = "0.10.0"
fxhash = "0.2.1"
indexmap = "2.11.3"
itertools = "0.14.0"
lazy_static = "1.5.0"
rayon = "1.11.0"
smallvec = "1.15.1"

[features]
flamegraph = []

[profile.release]
debug = true
