# The free 677 magma as described here: https://teorth.github.io/equational_theories/blueprint/677-chapter.html

# Term t ::= (t, t) | string

# x < y
def lt(x, y):
    if type(y) != tuple:
        return False
    return x == y[0] or x == y[1] or lt(x, y[0]) or lt(x, y[1])

def f(x, y):
    if not lt(x, y):
        return (x, y)
    yl = y[0]
    if y[1] == f(f(x, yl), x):
        return yl
    return (x, y)

X = "x"
Y = "y"
# critical pair generated by twee:
a = f(X, f(f(Y, f(f(X, Y), X)), f(Y, X)))
b = f(Y, f(f(X, Y), X))

print(a)
print(b)
